<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = array(
                'myfirstblog_controller_blog' => '/MyFirstBlog/Controller/Blog.php',
                'myfirstblog_datamapper_entry' => '/MyFirstBlog/DataMapper/Entry.php',
                'myfirstblog_model_entry' => '/MyFirstBlog/Model/Entry.php'
            );
        
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ .'/app'. $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
