<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
  function ($class) {
    static $classes = null;
    if ($classes === null) {
      $classes = array(
        'pimf_application'                => '/Pimf/Application.php',
        'pimf_cache'                      => '/Pimf/Cache.php',
        'pimf_cache_storages_apc'         => '/Pimf/Cache/Storages/Apc.php',
        'pimf_cache_storages_dba'         => '/Pimf/Cache/Storages/Dba.php',
        'pimf_cache_storages_file'        => '/Pimf/Cache/Storages/File.php',
        'pimf_cache_storages_memcached'   => '/Pimf/Cache/Storages/Memcached.php',
        'pimf_cache_storages_memory'      => '/Pimf/Cache/Storages/Memory.php',
        'pimf_cache_storages_pdo'         => '/Pimf/Cache/Storages/Pdo.php',
        'pimf_cache_storages_redis'       => '/Pimf/Cache/Storages/Redis.php',
        'pimf_cache_storages_storage'     => '/Pimf/Cache/Storages/Storage.php',
        'pimf_cache_storages_wincache'    => '/Pimf/Cache/Storages/Wincache.php',
        'pimf_cli'                        => '/Pimf/Cli.php',
        'pimf_cli_color'                  => '/Pimf/Cli/Color.php',
        'pimf_cli_io'                     => '/Pimf/Cli/Io.php',
        'pimf_controller_abstract'        => '/Pimf/Controller/Abstract.php',
        'pimf_controller_core'            => '/Pimf/Controller/Core.php',
        'pimf_controller_exception'       => '/Pimf/Controller/Exception.php',
        'pimf_cookie'                     => '/Pimf/Cookie.php',
        'pimf_datamapper_abstract'        => '/Pimf/DataMapper/Abstract.php',
        'pimf_entitymanager'              => '/Pimf/EntityManager.php',
        'pimf_environment'                => '/Pimf/Environment.php',
        'pimf_error'                      => '/Pimf/Error.php',
        'pimf_event'                      => '/Pimf/Event.php',
        'pimf_logger'                     => '/Pimf/Logger.php',
        'pimf_memcached'                  => '/Pimf/Memcached.php',
        'pimf_model_toarray'              => '/Pimf/Model/ToArray.php',
        'pimf_param'                      => '/Pimf/Param.php',
        'pimf_pdo'                        => '/Pimf/Pdo.php',
        'pimf_pdo_connector'              => '/Pimf/Pdo/Connector.php',
        'pimf_pdo_factory'                => '/Pimf/Pdo/Factory.php',
        'pimf_pdo_mysql'                  => '/Pimf/Pdo/Mysql.php',
        'pimf_pdo_postgre'                => '/Pimf/Pdo/Postgre.php',
        'pimf_pdo_sqlite'                 => '/Pimf/Pdo/Sqlite.php',
        'pimf_pdo_sqlserver'              => '/Pimf/Pdo/Sqlserver.php',
        'pimf_redis'                      => '/Pimf/Redis.php',
        'pimf_registry'                   => '/Pimf/Registry.php',
        'pimf_request'                    => '/Pimf/Request.php',
        'pimf_resolver'                   => '/Pimf/Resolver.php',
        'pimf_resolver_exception'         => '/Pimf/Resolver/Exception.php',
        'pimf_session'                    => '/Pimf/Session.php',
        'pimf_session_payload'            => '/Pimf/Session/Payload.php',
        'pimf_session_storages_apc'       => '/Pimf/Session/Storages/Apc.php',
        'pimf_session_storages_cookie'    => '/Pimf/Session/Storages/Cookie.php',
        'pimf_session_storages_dba'       => '/Pimf/Session/Storages/Dba.php',
        'pimf_session_storages_file'      => '/Pimf/Session/Storages/File.php',
        'pimf_session_storages_memcached' => '/Pimf/Session/Storages/Memcached.php',
        'pimf_session_storages_memory'    => '/Pimf/Session/Storages/Memory.php',
        'pimf_session_storages_pdo'       => '/Pimf/Session/Storages/Pdo.php',
        'pimf_session_storages_redis'     => '/Pimf/Session/Storages/Redis.php',
        'pimf_session_storages_storage'   => '/Pimf/Session/Storages/Storage.php',
        'pimf_util_cache'                 => '/Pimf/Util/Cache.php',
        'pimf_util_crypter'               => '/Pimf/Util/Crypter.php',
        'pimf_util_csv'                   => '/Pimf/Util/Csv.php',
        'pimf_util_enum'                  => '/Pimf/Util/Enum.php',
        'pimf_util_file'                  => '/Pimf/Util/File.php',
        'pimf_util_fluent'                => '/Pimf/Util/Fluent.php',
        'pimf_util_header'                => '/Pimf/Util/Header.php',
        'pimf_util_identifier'            => '/Pimf/Util/Identifier.php',
        'pimf_util_identitymap'           => '/Pimf/Util/IdentityMap.php',
        'pimf_util_json'                  => '/Pimf/Util/Json.php',
        'pimf_util_ldap'                  => '/Pimf/Util/Ldap.php',
        'pimf_util_memoryusage'           => '/Pimf/Util/MemoryUsage.php',
        'pimf_util_message'               => '/Pimf/Util/Message.php',
        'pimf_util_serializer'            => '/Pimf/Util/Serializer.php',
        'pimf_util_string'                => '/Pimf/Util/String.php',
        'pimf_util_uploadedfile'          => '/Pimf/Util/UploadedFile.php',
        'pimf_util_uuid'                  => '/Pimf/Util/Uuid.php',
        'pimf_util_validator'             => '/Pimf/Util/Validator.php',
        'pimf_util_value'                 => '/Pimf/Util/Value.php',
        'pimf_util_xml'                   => '/Pimf/Util/Xml.php',
        'pimf_util_linebyline'            => '/Pimf/Util/LineByLine.php',
        'pimf_view'                       => '/Pimf/View.php',
        'pimf_view_haanga'                => '/Pimf/View/Haanga.php',
        'pimf_view_json'                  => '/Pimf/View/Json.php',
        'pimf_view_twig'                  => '/Pimf/View/Twig.php',
        'pimf_contracts_reunitable'       => '/Pimf/Contracts/Reunitable.php',
        'pimf_contracts_arrayable'        => '/Pimf/Contracts/Arrayable.php',
        'pimf_contracts_jsonable'         => '/Pimf/Contracts/Jsonable.php',
        'pimf_contracts_messageprovider'  => '/Pimf/Contracts/MessageProvider.php',
        'pimf_contracts_renderable'       => '/Pimf/Contracts/Renderable.php',
        'pimf_contracts_cleanable'        => '/Pimf/Contracts/Cleanable.php',
      );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
      require __DIR__ . '/core' . $classes[$cn];
    }

    return false;
  }
);
// @codeCoverageIgnoreEnd